import express from 'express';
import { UserController } from '../../../controllers/UserController.js';
import { authenticationUser } from '../../Middleware/Auth.js';
var router = express.Router();
const User_Controller = new UserController();
router.post('/', User_Controller.save_user);
router.get('/:id', authenticationUser, User_Controller.get_user);
//router.delete('/:id', authentication, User_Controller.delete_user); 
router.put('/:id', authenticationUser, User_Controller.update_user);
export default router;